---
title: "A molecular approach to study Hymenoptera diets using wasp nests"
author: 
- name: Marie-Caroline Lefort
  orcid: 0000-0002-7031-9864
- name: Jacqueline R. Beggs
  orcid: 0000-0002-2112-2803
- name: Travis R. Glare
  orcid: 0000-0001-7795-8709
- name: Thomas E. Saunders
  orcid: 0000-0003-1780-0314
- name: Erin J. Doyle
  orcid: 0000-0001-5259-3715 
- name: Stéphane Boyer
  orcid: 0000-0002-0750-4864
date: "2020-11-13"
categories:
  - Peer Reviewed
  - Environmental DNA
  - Metabarcoding
  - Social Insects
  - Trophic Interactions
subtitle: "*NeoBiota*"
description: "DNA analysis of social wasp larval frass to examine the identity and seasonality of prey communities."
---
<div class="meta-heading-links">Links</div>

[{{< iconify fluent:document-20-filled >}} **Publication**](https://doi.org/10.7717/peerj.4642){.btn .btn-outline-primary .btn role="button"} &nbsp; [{{< iconify academicons:biorxiv >}} **Preprint**](https://doi.org/10.1101/2020.04.06.024422){.btn .btn-outline-primary .btn role="button"}

## Abstract

The study of animal diets has benefited from the rise of high-throughput DNA sequencing applied to stomach content or faecal samples. The latter can be fresh samples used to describe recent meals or older samples, which can provide information about past feeding activities. For most invertebrates, however, it is difficult to access ‘historical’ samples, due to the small size of the animals and the absence of permanent defecation sites. Therefore, sampling must be repeated to account for seasonal variation and to capture the overall diet of a species.

This study develops a method to describe the overall diet of nest-building Hymenoptera, based on a single sampling event, by analysing prey DNA from faeces accumulated in brood cells. We collected 48 nests from two species of introduced paper wasps (*Polistes chinensis* Fabricius and *P. humilis* Fabricius) in the urban and peri-urban areas of Auckland, New Zealand and selected two samples per nest. One from brood cells in the outer layer of the nest to represent the most recent diet and one from brood cells in an inner layer to represent older diet.

Diet differed between species, although both fed mainly on Thysanoptera, Lepidoptera and Acariformes. Prey taxa identified to species level included both agricultural pests and native species. Prey communities consumed were significantly different between inner and outer nest samples, suggesting seasonal variation in prey availability and/or a diversification of the wasps’ diet as the colony grows. We also show for the first time potential predation of marine organisms by *Polistes* wasps.

Our study provides field evidence that *Polistes* wasps feed on agricultural pests, supporting the hypothesis that some social wasp species could have a suppressing effect on agricultural pests. The proposed methodology is readily applicable to other nest-building Hymenoptera and has the potential to provide comprehensive knowledge about their diet with minimum sampling effort. Such knowledge is essential to measure the ecological impact of invasive Vespidae and support the conservation of native invertebrate biodiversity.
