---
title: "Improving pre-release risk assessments for classical biological control agents by integrating behavioural, electrophysiological, and chemical-ecological methods for host specificity testing"
author: 
- name: Thomas E. Saunders
  orcid: 0000-0003-1780-0314
date: "2022-03-16"
categories:
  - Thesis
  - Biological Control
  - Ecological Host Range
  - Non-target Risks
  - Electroantennography
  - Arrestment
  - Oviposition Tests
  - Pentatomidae
  - Scelionidae
subtitle: "*University of Auckland*"
description: "Doctoral thesis investigating methods for host-specificity testing of proposed biological control agents, including oviposition tests, electroantennography, arrestment experiments, and competition tests."
---
<div class="meta-heading-links">Links</div>

[{{< iconify mdi:graduation-cap >}} **Thesis**](https://hdl.handle.net/2292/58529){.btn .btn-outline-primary .btn role="button"} 

## Abstract

Classical biological control has proven to be a cost-effective method of suppressing pest populations in a variety of contexts, but it requires a thorough assessment of the potential nontarget risks posed by a candidate agent in order to be environmentally safe. Pre-release host specificity testing is a cornerstone of safe and effective biological control programmes, and some kind of risk assessment is usually required by national regulators before a new organsim can be released. Decision makers often have to evaluate applications to release biological control agents (BCAs) based on physiological host range tests conducted in containment. For parasitoid agents, these usually manifest as no-choice oviposition tests, where a candidate BCA is confined in close proximity with a series of non-target species. These kinds of host range tests are a crucial first step in assessing host specificity because they offer unambiguous evidence of the ability of a BCA to recognise, attack, and develop in non-target species, thus confirming that species as a physiological host. However, the simplicity and artificiality of these tests are both an asset and a potential drawback. Physiological host range tests necessarily remove many important chemical cues from the host location process that parasitoids rely on for the natural expression of their ecological host ranges (the list of species they will actually attack in the field). The discrepancy between physiological and ecological host range has important implications for whether or not the candidate agent will be approved for release, and whether or not it will attack non-target species in the natural environment. 

The primary aim of my thesis was to apply chemical ecological methods to the study of host specificity, with a view toward integrating these methods into pre-release non-target risk assessments to provide more certainty to regulators about the risks a candidate agent may pose. My case study was the host-parasitoid complex of New Zealand stink bugs (Hemiptera: Pentatomidae) and three of their egg parasitoids (Hymenoptera: Scelionidae). New Zealand Pentatomidae taxa include: *Cermatulus nasalis hudsoni* Woodward, *Cermatulus nasalis nasalis* (Woodward), *Cermatulus nasalis turbotti* Woodward, *Cuspicona simplex* Walker, *Dictyotus caenosus* (Westwood), *Glaucias amyoti* (Dalla), *Hypsithocus hudsonae* Bergroth, *Monteithiella humeralis* Walker, *Nezara viridula* (L.), and *Oechalia schellenbergii* (Guérin). Egg parasitoids included: *Trissolcus japonicus* Ashmead, a BCA of brown marmorated stink bug (*Halyomorpha halys* Stål) conditionally approved for release in New Zealand in the event of the establishment of its target host; *Trissolcus basalis* (Wollaston), a BCA of green vegetable bug (*Nezara viridula* [L.]) introduced into New Zealand in 1949; and *Trissolcus oenone* Johnson, a pentatomid parasitoid native to Australia and New Zealand. 

Physiological host range testing of all three parasitoids revealed all were capable of attacking and developing in all pentatomid species tested, except *N. viridula* was not a host of *T. japonicus* and *T. oenone*, and *T. oenone* was unable to be tested with the endemic pentatomid *Hypsithocus hudsonae* (Bergroth). Development times were similar for the two resident New Zealand parasitoids on all pentatomid species. *Trissolcus japonicus* was shown to be capable of high parasitism rates against the endemic alpine shield bug, *H. hudsonae*. 

The integration of electroantennography with open arena arrestment bioassays and competition tests helped to reveal the host preferences of *T. basalis* and *T. oenone* in relation to the exotic pentatomids *N. viridula* and *Cuspicona simplex* (Walker). Acetone extracts of *N. viridula* eggs elicited clear and consistent antennal responses in *T. basalis*, and these responses were stronger than those elicited by a hexane extract. Potential contact kairomones on the surfaces of eggs were tentatively identified to provide a foundation for future study in this area. Open arena arrestment bioassays were used to compare the retention time of the two parasitoids in arenas contaminated by one of the two pentatomid species. *Trissolcus basalis* spent four times longer searching in arenas for its primary host, *N. viridula*, than for *C. simplex*, while the reverse was true for *T. oenone*, which spent an even lower absolute length of time searching for *N. viridula*, a non-host. Parasitoids are therefore capable of distinguishing between these hosts based solely on adult footprint compounds left on substrates, and *T. oenone* is potentially capable of distinguishing between hosts and non-hosts. 

Competition tests between the two parasitoids on *C. simplex eggs* revealed *T. oenone* to be the superior competitor in both extrinsic and intrinsic contests. The native parasitoid successfully parasitized more eggs than *T. basalis*, and developed in over 90% of multiparasitised eggs. The combination of these approaches was useful for investigating the influence of chemical cues on the expression of host range. In particular, the results of arrestment studies clearly complement physiological host range tests and help to provide significant context especially when parasitism rates are similar. 

The specific compounds associated with New Zealand species of stink bugs which elicit antennal responses in the three *Trissolcus* parasitoids were revealed through a combination of electrophysiological techniques and chemical analyses. Cuticular hydrocarbons and defensive compounds were extracted from adult stink bugs via immersion in hexane, and the resulting samples were analysed through GC-MS to identify the compounds present. Extracts were then exposed to the three species of parasitoids through gas chromatography coupled with electroantennographic detection (GC-EAD), which measures the change in voltage across an insect antenna as compounds from an extract are fractionated and passed over its surface. After GC-EAD with extract, another round of recordings were made with synthetic standards. A final round of electroantennogram recordings were made by puffing individual compounds over the antennae and comparing responses to solvent controls. A total of eight compounds elicited responses, and seven of these were identified as follows: (E)-2-decenal, (E)-2-octenal, (E)-4- oxo-2-hexenal, (E)-2-hexenal, (E)-2-decenyl acetate, n-tridecane, and n-dodecane. This work provides the foundation for future studies of the behavioural function of these compounds in stink bug egg parasitoids. 

The work presented in this thesis shows the value of incorporating chemical ecological techniques into the study of host specificity, and for evaluating the non-target risks posed by classical BCAs. The results of olfactory and electrophysiological methods are complementary to physiological host range testing, and the combination of methods provides valuable insight into the chemical basis of host range. These kinds of studies provide results which are directly relevant for regulators to consider during the evaluation of applications to release new BCAs. A new non-target risk assessment framework incorporating these techniques is proposed.

